name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
   - cron: "0 */3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Get acces to spotify api
      run: |
        curl -sSL https://git.io/install-xq | sudo bash
        curl -s -X "POST" -H "Authorization: Basic ${{ secrets.SPOTIFY_API }}" -d grant_type=client_credentials https://accounts.spotify.com/api/token | jq '.access_token' | tr -d '"' > token
        echo "BEARER=$(cat token)" >> $GITHUB_ENV
    #- name: Set env
    #  run: echo "BEARER=$(echo ${{ secrets.BEARER }})" >> $GITHUB_ENV
    #- name: Test
    #  run: echo $BEARER
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: info
      run: php feed.php
    - name: tidy
      run: cat feed2.rss | xq > feed3.rss
    - name: Commit report
      run: |
        git config --global user.name 'MikeeI'
        git config --global user.email 'MikeeI@users.noreply.github.com'
        git add -A
        git commit -am "Automated report"
        git push
    - name: ls
      run: ls -lah
